# Generated by Django 3.1 on 2020-10-21 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoControl',
            fields=[
                ('ICA', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombreproductocontrol', models.CharField(max_length=100)),
                ('frecuencia', models.PositiveIntegerField()),
                ('valor', models.PositiveIntegerField()),
                ('tiproducto', models.CharField(choices=[('CH', 'Control Hongo'), ('CP', 'Control Plaga'), ('CF', 'Control Fertilizante')], max_length=2)),
                ('periodocarencia', models.DateField(blank=True)),
                ('fechaaplicado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El primer nombre debe tener al menos 3 letras')])),
                ('nombre2', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El segundo nombre debe tener al menos 3 letras')])),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('IdAs', models.CharField(max_length=60, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2, 'El ID asignado es muy corto'), django.core.validators.MaxLengthValidator(60, 'El ID asignado es muy largo')])),
                ('nombrevivero', models.CharField(max_length=60)),
                ('municipio', models.CharField(max_length=40)),
                ('departamento', models.CharField(max_length=40)),
                ('planta', models.CharField(max_length=100)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveros.productor')),
            ],
        ),
    ]
