# Generated by Django 3.1 on 2020-10-21 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='apellido1',
            field=models.CharField(default='Perez', max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El primer apellido debe tener al menos 3 letras')]),
        ),
        migrations.AddField(
            model_name='productor',
            name='apellido2',
            field=models.CharField(default='Perez', max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El segundo apellido debe tener al menos 3 letras')]),
        ),
        migrations.AlterField(
            model_name='productor',
            name='nombre2',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El segundo nombre debe tener al menos 3 letras')]),
        ),
    ]
