# Generated by Django 3.1 on 2020-10-22 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_auto_20201021_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocontrol',
            name='periodocarencia',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
