# Generated by Django 3.1 on 2020-10-22 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0003_auto_20201022_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocontrol',
            old_name='nombreproductocontrol',
            new_name='nombre_producto_control',
        ),
        migrations.RenameField(
            model_name='productocontrol',
            old_name='periodocarencia',
            new_name='periodo_de_carencia',
        ),
        migrations.RenameField(
            model_name='productocontrol',
            old_name='tiproducto',
            new_name='tipo_de_producto',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='apellido1',
            new_name='apellido_1',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='apellido2',
            new_name='apellido_2',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='nombre1',
            new_name='nombre_1',
        ),
        migrations.RenameField(
            model_name='productor',
            old_name='nombre2',
            new_name='nombre_2',
        ),
        migrations.RenameField(
            model_name='vivero',
            old_name='nombrevivero',
            new_name='nombre_vivero',
        ),
        migrations.RemoveField(
            model_name='productocontrol',
            name='fechaaplicado',
        ),
        migrations.AddField(
            model_name='productocontrol',
            name='fecha_aplicado',
            field=models.DateField(default=datetime.date.today, help_text='AAAA-MM-DD'),
        ),
        migrations.AlterField(
            model_name='productocontrol',
            name='frecuencia',
            field=models.PositiveIntegerField(help_text='Frecuencia de aplicado en dias'),
        ),
        migrations.AlterField(
            model_name='productocontrol',
            name='valor',
            field=models.PositiveIntegerField(verbose_name='Valor del producto de control'),
        ),
    ]
