# Generated by Django 3.1 on 2020-10-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0004_auto_20201022_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocontrol',
            name='periodo_de_carencia',
        ),
    ]
