# Generated by Django 3.1 on 2020-10-22 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0006_remove_productocontrol_fecha_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='productocontrol',
            name='valor',
            field=models.PositiveIntegerField(help_text='Valor del producto de control'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='apellido_1',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El primer apellido debe tener al menos 3 letras')]),
        ),
        migrations.AlterField(
            model_name='productor',
            name='apellido_2',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'El segundo apellido debe tener al menos 3 letras')]),
        ),
    ]
