# Generated by Django 3.1 on 2020-10-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0007_auto_20201022_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254, unique=True),
        ),
    ]
