# Generated by Django 3.1 on 2020-10-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0009_auto_20201022_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocontrol',
            name='nombre_hongo_afectado',
        ),
        migrations.RemoveField(
            model_name='productocontrol',
            name='periodo_de_carencia',
        ),
        migrations.RemoveField(
            model_name='productocontrol',
            name='tipo_de_producto',
        ),
    ]
