# Generated by Django 3.1 on 2020-10-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0010_auto_20201022_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocontrol',
            name='nombre_hongo_afectado',
            field=models.CharField(blank=True, default='Seta', help_text='Si aplica', max_length=100),
        ),
        migrations.AddField(
            model_name='productocontrol',
            name='periodo_de_carencia',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Si aplica, en dias'),
        ),
        migrations.AddField(
            model_name='productocontrol',
            name='tipo_de_producto',
            field=models.CharField(choices=[('CH', 'Control Hongo'), ('CP', 'Control Plaga'), ('CF', 'Control Fertilizante')], default='CH', max_length=2),
        ),
    ]
