# Generated by Django 3.1 on 2020-10-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0011_auto_20201022_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocontrol',
            name='periodo_de_carencia',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Si aplica, en dias', null=True),
        ),
    ]
