# Generated by Django 3.1 on 2020-10-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0013_auto_20201022_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocontrol',
            name='tipo_de_producto',
            field=models.CharField(choices=[('CH', 'Control Hongo'), ('CP', 'Control Plaga'), ('CF', 'Control Fertilizante')], max_length=2),
        ),
    ]
