# Generated by Django 3.1 on 2020-10-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0014_auto_20201022_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoControlFertilizante',
            fields=[
                ('productocontrol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viveros.productocontrol')),
            ],
            bases=('viveros.productocontrol',),
        ),
        migrations.RemoveField(
            model_name='productocontrol',
            name='nombre_hongo_afectado',
        ),
        migrations.RemoveField(
            model_name='productocontrol',
            name='periodo_de_carencia',
        ),
        migrations.RemoveField(
            model_name='productocontrol',
            name='tipo_de_producto',
        ),
        migrations.CreateModel(
            name='ProductoControlHongo',
            fields=[
                ('productocontrol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viveros.productocontrol')),
                ('periodo_de_carencia', models.PositiveIntegerField(blank=True, default=1, help_text='Si aplica, en dias', null=True)),
                ('nombre_hongo_afectado', models.CharField(blank=True, default='Seta', help_text='Si aplica', max_length=100, null=True)),
            ],
            bases=('viveros.productocontrol',),
        ),
        migrations.CreateModel(
            name='ProductoControlPlaga',
            fields=[
                ('productocontrol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viveros.productocontrol')),
                ('periodo_de_carencia', models.PositiveIntegerField(blank=True, default=1, help_text='Si aplica, en dias', null=True)),
            ],
            bases=('viveros.productocontrol',),
        ),
    ]
