# Generated by Django 3.1 on 2020-10-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0015_auto_20201027_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocontrolhongo',
            name='nombre_hongo_afectado',
            field=models.CharField(default='Seta', max_length=100),
        ),
        migrations.AlterField(
            model_name='productocontrolhongo',
            name='periodo_de_carencia',
            field=models.PositiveIntegerField(default=1, help_text='En dias'),
        ),
        migrations.AlterField(
            model_name='productocontrolplaga',
            name='periodo_de_carencia',
            field=models.PositiveIntegerField(default=1, help_text='En dias'),
        ),
    ]
