# Generated by Django 3.1 on 2020-11-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0016_auto_20201028_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Trabajo realizado', max_length=1000)),
                ('fecha', models.DateField(auto_now=True)),
                ('IdAs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viveros.vivero')),
                ('producto_fertilizante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='viveros.productocontrolfertilizante')),
                ('producto_hongo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='viveros.productocontrolhongo')),
                ('producto_plaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='viveros.productocontrolplaga')),
            ],
        ),
    ]
