# Generated by Django 3.1 on 2020-11-03 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0017_labor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='producto_fertilizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='viveros.productocontrolfertilizante'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='producto_hongo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='viveros.productocontrolhongo'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='producto_plaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='viveros.productocontrolplaga'),
        ),
    ]
