# Generated by Django 3.1 on 2020-11-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0018_auto_20201102_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('productor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viveros.productor')),
                ('correo2', models.EmailField(default='correo@ejemplo.com', max_length=254, unique=True)),
            ],
            bases=('viveros.productor',),
        ),
    ]
