# Generated by Django 3.1 on 2020-11-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0020_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
