# Generated by Django 3.1 on 2020-10-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0005_auto_20201028_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='states',
            new_name='name',
        ),
    ]
