# Generated by Django 3.1 on 2020-10-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0007_auto_20201028_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
    ]
