# Generated by Django 3.1 on 2020-10-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0008_auto_20201028_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
    ]
